# use src.git with url to follow latest commit

[mpv-chapterskip]
src.git = "https://github.com/iynaix/chapterskip"
fetch.github = "iynaix/chapterskip"

[mpv-deletefile]
src.git = "https://github.com/zenyd/mpv-scripts"
fetch.github = "zenyd/mpv-scripts"

[mpv-modernx]
src.git = "https://github.com/cyl0/ModernX"
fetch.github = "cyl0/ModernX"

[mpv-nextfile]
src.git = "https://github.com/jonniek/mpv-nextfile"
fetch.github = "jonniek/mpv-nextfile"

[mpv-sub-select]
src.git = "https://github.com/CogentRedTester/mpv-sub-select"
fetch.github = "CogentRedTester/mpv-sub-select"

[mpv-subsearch]
src.git = "https://github.com/kelciour/mpv-scripts"
fetch.github = "kelciour/mpv-scripts"

[mpv-thumbfast-osc]
src.git = "https://github.com/l-jared/thumbfast"
src.branch = "vanilla-osc"
fetch.github = "l-jared/thumbfast"

[path-of-building]
src.github_tag = "PathOfBuildingCommunity/PathOfBuilding"
fetch.github = "PathOfBuildingCommunity/PathOfBuilding"

[swww]
src.git = "https://github.com/Horus645/swww"
fetch.github = "Horus645/swww"

[transmission-web-soft-theme]
src.git = "https://github.com/diesys/transmission-web-soft-theme"
fetch.github = "diesys/transmission-web-soft-theme"

[vv]
src.github_tag = "hackerb9/vv"
fetch.github = "hackerb9/vv"

[waybar]
src.git = "https://github.com/Alexays/Waybar"
fetch.github = "Alexays/Waybar"